### ISSUE TITLE
Visual form builder

### ISSUE THREAD

**Issue by flauc** [Jaspero/jms#34]
I think we should start by building a mockup for this part

**Comment by Siclol** [comment]
A few notes of how I think it should work.

#### Free up screen space

First thing I would like to do is move "Module info" card out of the way. I think that is achievable by adding a settings icon on the top bar that will open a dialog for name/desc/id. In case of creating a new module, once the user wants to click "Save", it can pop up a dialog to give the module a name/desc/id.

One more thing to add into the "Module settings" dialog would be 2 radio buttons for code-editor and for visual-builder (default).


#### Flow

Now that we have a blank canvas, building a module follows simple steps: 
1. Create a segment (repeatable) [button].
2. Create fields in a segment (repeatable) [button].


#### Segment and field options

Since we want the visual-builder to visually replicate what it will look like, I wouldn't want to add any additional buttons to anything (e.g. "Edit" button when you hover a segment). I think we can keep it simple and make it so that when you click on a segment (e.g. white-space in a card) it opens up segment options. When you click on an input, it opens up options for that field.

I think these options should appear as a sidebar in order for the user to still be able to see (atleast partially) what his form looks like.

**Comment by Siclol** [comment]
@flauc  :)

- [ ] Move "Module info" to a dialog (I've moved it but it's not connected)
- [ ] Inside "Module info dialog", connect "Default view" radio buttons to toggle between Visual form builder and Schema code builder. Outside of the dialog, I've put Visual form builder inside `<ng-container *ngIf="1">`, and Schema code builder inside `<ng-container *ngIf="0">` temporarily. This just needs to correspond with dialog radio buttons.
- [ ] Move sidebar `<section class="jms-definition-instance-sidebar active">` to it's own component (I assume).
- [ ] Connect sidebar active class.
- [ ] Clicking on a segment opens the sidebar with options for that segment. Segments have the "Duplicate" option in sidebar-header
- [ ] Clicking on a field opens the sidebar with options for that field.
- [ ] Fields can be dragged to reorder.
- [ ] Connect "Add segment" button.
- [ ] Connect "Add field" button.
- [ ] Clean up anything I've added to make things temporarily visible (segment, field, dialog).

**Comment by Siclol** [comment]
@flauc 
@flauc 

Futhermore, since module info is now "hidden" in a dialog, if a user comes to create a new module, he/she creates segments & fields, and then wants to click save, it should pop up a dialog to add a name for the dialog (in case the user hasn't manually done that already).
