### ISSUE TITLE
Remove this symbol from default parameters 

### ISSUE THREAD

**Issue by bridget75** [Jaspero/jms#407]
I am not sure why is this happening, I am not even sure this is problem with CMS. I am able to see second project with the same " bug" so I am assuming this is CMS problem (some symbol is added)

![image](https://user-images.githubusercontent.com/93909566/191957697-9c3c1d81-a02c-450c-a66e-a7a0a699ff5d.png)

**Comment by flauc** [comment]
@bridget75 this was actually a schema forms issue. This character was copied over from somewhere else and we allowed it to happen instead of stripping it of. The issue has been resolved on schema forms. However, this only means the issue shouldn't happen again the character needs to be removed manually in places it already exists.
